name: yourpods
version: '1.0.0+17'
summary: A self-hosted podcast player.
description: |
  YourPods is a self-hosted podcast player that connects to your gpodder compatible server.

confinement: strict
base: core22
grade: stable

apps:
  yourpods:
    command: yourpods
    extensions: [flutter]
    plugs:
      - network
      - audio-playback
      - password-manager-service

parts:
  yourpods:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
